/**
 * =============================================================================
 *  Multilingual support — English · Urdu · Roman Urdu · Punjabi
 * =============================================================================
 *
 *  Two responsibilities:
 *
 *   1. `detectLanguage()` — a dependency-free heuristic that classifies a user
 *      message so the AI layer can be told which language to mirror and so the
 *      UI can switch text direction. It deliberately errs towards English when
 *      confidence is low; the model itself does the final, nuanced matching.
 *
 *   2. `t()` — a tiny dictionary for the handful of UI strings that must be
 *      localised outside the model (welcome screen, buttons, composer). Full
 *      page copy stays in English; conversational content is generated by the
 *      model in the user's language.
 *
 *  Isomorphic — safe to import from client components.
 * =============================================================================
 */

export type Language = "en" | "ur" | "ur_roman" | "pa";

export const LANGUAGES: readonly Language[] = ["en", "ur", "ur_roman", "pa"] as const;

export interface LanguageProfile {
  id: Language;
  /** English label. */
  label: string;
  /** Label written in the language itself. */
  nativeLabel: string;
  /** BCP-47 tag used for speech synthesis / recognition. */
  speechTag: string;
  /** Whether the script renders right-to-left. */
  rtl: boolean;
  /** Instruction injected into the system prompt. */
  promptDirective: string;
}

export const LANGUAGE_PROFILES: Record<Language, LanguageProfile> = {
  en: {
    id: "en",
    label: "English",
    nativeLabel: "English",
    speechTag: "en-US",
    rtl: false,
    promptDirective: "Reply in clear, professional English.",
  },
  ur: {
    id: "ur",
    label: "Urdu",
    nativeLabel: "اردو",
    speechTag: "ur-PK",
    rtl: true,
    promptDirective:
      "Reply in simple, natural Urdu using Urdu script. Keep technical product names in English (e.g. WhatsApp, SEO, AI).",
  },
  ur_roman: {
    id: "ur_roman",
    label: "Roman Urdu",
    nativeLabel: "Roman Urdu",
    speechTag: "ur-PK",
    rtl: false,
    promptDirective:
      "Reply in Roman Urdu (Urdu written in Latin script), the way people chat on WhatsApp. Friendly and simple. Keep technical product names in English.",
  },
  pa: {
    id: "pa",
    label: "Punjabi",
    nativeLabel: "پنجابی",
    speechTag: "pa-IN",
    rtl: true,
    promptDirective:
      "Reply in warm, conversational Punjabi (Shahmukhi script, as written in Pakistan). Keep technical product names in English.",
  },
};

/** Urdu / Arabic script range used to distinguish scripts. */
const ARABIC_SCRIPT = /[؀-ۿݐ-ݿﭐ-﷿ﹰ-﻿]/;

/** Words that appear in Punjabi (Shahmukhi) far more often than in Urdu. */
const PUNJABI_SCRIPT_MARKERS = [
  "تُسی",
  "تسی",
  "اسی",
  "کِنج",
  "کیویں",
  "ہَیگا",
  "ہَے نا",
  "میں تینوں",
  "تینوں",
  "سانوں",
  "ودھیا",
  "چنگا",
  "گل",
  "نال",
  "لئی",
  "دسو",
  "کر دیو",
];

/** Roman-script tokens that reliably signal Roman Urdu. */
const ROMAN_URDU_MARKERS = [
  "aap", "ap ", "kya", "kia", "kaise", "kese", "kesay", "kaisay", "hai", "hain",
  "nahi", "nahin", "mujhe", "mujhy", "mera", "meri", "hum", "tum", "kitna",
  "kitni", "kitne", "chahiye", "chahye", "batao", "bataen", "bta", "krna",
  "karna", "kar", "acha", "theek", "thik", "shukriya", "salam", "assalam",
  "janab", "bhai", "sir ji", "ji han", "jee", "please batao", "fees kitni",
  "course ka", "kaam", "sikhna", "seekhna", "paisa", "rupay", "waqt",
];

/**
 * Roman-script tokens that lean Punjabi rather than Urdu.
 *
 * Includes the full verb paradigm (karda/kardi/karde/karan) and the Punjabi
 * question words, because a single form is rarely enough: "tusi kihda kam
 * karde ho" only hits `tusi` if `karde` and `kihda` are missing, which drops
 * it below the two-marker threshold and misclassifies it as English.
 */
const ROMAN_PUNJABI_MARKERS = [
  // Pronouns
  "tusi", "tussi", "tuhada", "tuhadi", "tuhanu", "asi", "assi", "sanu",
  "menu ", "mainu", "ohna", "ohde",
  // Question words
  "kiddan", "kidan", "kihda", "kehda", "kihdi", "kine", "kinna", "kinni",
  "ki haal", "ki gall", "kyu ji",
  // Verbs — Punjabi conjugations
  "karda", "kardi", "karde", "karan", "hunda", "hundi", "hunde",
  "gaya si", "aaya si", "dasso", "dasso ji", "dassan",
  // Common vocabulary
  "changa", "wadhiya", "vadhiya", "sohna", "sohni", "gall", "gallan",
  "naal", "labhna", "chahida", "bilkul ji",
];

/**
 * Classify the language of a message.
 *
 * Order matters: script detection first (unambiguous), then Roman-script
 * keyword scoring. A single Roman marker is not enough — we require either two
 * distinct markers or a very short message dominated by one, which keeps
 * English sentences containing "hai" or "ap" from being misclassified.
 */
export function detectLanguage(text: string): Language {
  const raw = (text ?? "").trim();
  if (!raw) return "en";

  if (ARABIC_SCRIPT.test(raw)) {
    const punjabiHits = PUNJABI_SCRIPT_MARKERS.filter((m) => raw.includes(m)).length;
    return punjabiHits >= 2 ? "pa" : "ur";
  }

  const lower = ` ${raw.toLowerCase().replace(/[^a-z0-9\s]/g, " ").replace(/\s+/g, " ")} `;
  const words = lower.trim().split(" ").filter(Boolean);

  const punjabiHits = countMarkers(lower, ROMAN_PUNJABI_MARKERS);
  const urduHits = countMarkers(lower, ROMAN_URDU_MARKERS);

  if (punjabiHits >= 2 || (punjabiHits >= 1 && words.length <= 4)) return "pa";
  if (urduHits >= 2 || (urduHits >= 1 && words.length <= 4)) return "ur_roman";

  return "en";
}

function countMarkers(haystack: string, markers: readonly string[]): number {
  let hits = 0;
  for (const marker of markers) {
    if (haystack.includes(marker.includes(" ") ? marker : ` ${marker} `)) hits += 1;
  }
  return hits;
}

/** True when the language renders right-to-left. */
export function isRtl(language: Language): boolean {
  return LANGUAGE_PROFILES[language].rtl;
}

/** Convenience for speech synthesis / recognition on arbitrary text. */
export function speechTagFor(text: string): string {
  return LANGUAGE_PROFILES[detectLanguage(text)].speechTag;
}

/** Narrow an untrusted value to a `Language`. */
export function asLanguage(value: unknown): Language | null {
  return LANGUAGES.includes(value as Language) ? (value as Language) : null;
}

// --------------------------------------------------------------- Dictionary --

type UiKey =
  | "welcome.title"
  | "welcome.subtitle"
  | "chat.placeholder"
  | "chat.online"
  | "chat.newChat"
  | "chat.menu"
  | "chat.voice"
  | "chat.emptyTitle"
  | "chat.disclaimer"
  | "chat.tryAsking";

const DICTIONARY: Record<UiKey, Record<Language, string>> = {
  "welcome.title": {
    en: "How can we grow your business?",
    ur: "ہم آپ کے کاروبار کو کیسے بڑھا سکتے ہیں؟",
    ur_roman: "Hum aap ke business ko kaise barha sakte hain?",
    pa: "اسی تہاڈے کاروبار نوں کیویں ودھا سکدے آں؟",
  },
  "welcome.subtitle": {
    en: "AI automation, software, digital growth and brand — ask in any language.",
    ur: "اے آئی آٹومیشن، سافٹ ویئر، ڈیجیٹل گروتھ اور برانڈ — کسی بھی زبان میں پوچھیں۔",
    ur_roman: "AI automation, software, digital growth aur brand — kisi bhi zabaan mein poochein.",
    pa: "اے آئی آٹومیشن، سافٹ ویئر، ڈیجیٹل گروتھ تے برانڈ — کسے وی زبان وچ پُچھو۔",
  },
  "chat.placeholder": {
    en: "Ask anything… (English, اردو, Roman Urdu or پنجابی)",
    ur: "کچھ بھی پوچھیں… (اردو یا انگریزی)",
    ur_roman: "Kuch bhi poochein… (Roman Urdu ya English)",
    pa: "کجھ وی پُچھو… (پنجابی یا انگریزی)",
  },
  "chat.online": {
    en: "Assistant online",
    ur: "اسسٹنٹ آن لائن",
    ur_roman: "Assistant online",
    pa: "اسسٹنٹ آن لائن",
  },
  "chat.newChat": {
    en: "New chat",
    ur: "نئی گفتگو",
    ur_roman: "Nayi chat",
    pa: "نویں گل بات",
  },
  "chat.menu": {
    en: "Menu",
    ur: "مینو",
    ur_roman: "Menu",
    pa: "مینو",
  },
  "chat.voice": {
    en: "Voice",
    ur: "آواز",
    ur_roman: "Voice",
    pa: "آواز",
  },
  "chat.emptyTitle": {
    en: "How can I help you today?",
    ur: "میں آج آپ کی کیا مدد کر سکتا ہوں؟",
    ur_roman: "Main aaj aap ki kya madad kar sakta hoon?",
    pa: "میں اج تہاڈی کیہ مدد کر سکنا واں؟",
  },
  "chat.disclaimer": {
    en: "The assistant can make mistakes. Please confirm prices and timelines with our team.",
    ur: "اسسٹنٹ سے غلطی ہو سکتی ہے۔ قیمت اور وقت ہماری ٹیم سے تصدیق کر لیں۔",
    ur_roman:
      "Assistant se ghalti ho sakti hai. Price aur timeline hamari team se confirm kar lein.",
    pa: "اسسٹنٹ کولوں غلطی ہو سکدی اے۔ ریٹ تے ٹائم لائن ساڈی ٹیم کولوں پکی کر لوو۔",
  },
  "chat.tryAsking": {
    en: "Try asking about…",
    ur: "ان کے بارے میں پوچھیں…",
    ur_roman: "In ke baare mein poochein…",
    pa: "ایہناں بارے پُچھو…",
  },
};

/** Translate a UI key. Falls back to English when a translation is missing. */
export function t(key: UiKey, language: Language = "en"): string {
  return DICTIONARY[key]?.[language] ?? DICTIONARY[key]?.en ?? key;
}
