import type { Language } from "@/lib/i18n";
import { BRAND } from "@/lib/brands";
import type { CapturedRecord } from "@/types";
import type { ReplyButton } from "./types";

/**
 * =============================================================================
 *  WhatsApp channel copy
 * =============================================================================
 *
 *  Everything the WhatsApp bot says that is *not* generated by the model: the
 *  welcome message, record receipts, escalation notices and the quick-action
 *  chips.
 *
 *  Kept out of `lib/i18n.ts` on purpose — that dictionary serves the web UI,
 *  where labels sit on buttons in a rendered page. These strings are chat
 *  messages: they need emoji, line breaks and a warmer register, and they are
 *  only ever read inside WhatsApp.
 * =============================================================================
 */

type Localised = Record<Language, string>;

export const ACTION_BUTTON_PREFIX = "act:";

function pick(copy: Localised, language: Language): string {
  return copy[language] ?? copy.en;
}

// ---------------------------------------------------------------- Welcome ---

const WELCOME: Localised = {
  en: "👋 *Welcome to BITSOL Marketing!*\n\nI'm your AI assistant. We build AI chatbots, WhatsApp automation, AI agents, websites, apps and complete brand systems for ambitious businesses.\n\nTell me a little about your business and what you're looking for, and I'll point you in the right direction.",
  ur: "👋 *بِٹسول مارکیٹنگ میں خوش آمدید!*\n\nمیں آپ کا اے آئی اسسٹنٹ ہوں۔ ہم اے آئی چیٹ بوٹس، واٹس ایپ آٹومیشن، اے آئی ایجنٹس، ویب سائٹس، ایپس اور مکمل برانڈ سسٹم بناتے ہیں۔\n\nاپنے کاروبار اور ضرورت کے بارے میں تھوڑا سا بتائیں، میں آپ کی صحیح رہنمائی کروں گا۔",
  ur_roman:
    "👋 *BITSOL Marketing mein khush aamdeed!*\n\nMain aap ka AI assistant hoon. Hum AI chatbots, WhatsApp automation, AI agents, websites, apps aur complete brand systems banate hain.\n\nApne business aur zaroorat ke baare mein thora sa bataen, main aap ki sahi rehnumai karunga.",
  pa: "👋 *بِٹسول مارکیٹنگ وچ جی آیاں نوں!*\n\nمیں تہاڈا اے آئی اسسٹنٹ آں۔ اسی اے آئی چیٹ بوٹ، واٹس ایپ آٹومیشن، اے آئی ایجنٹ، ویب سائٹاں، ایپاں تے پورے برانڈ سسٹم بݨاندے آں۔\n\nاپنے کاروبار تے لوڑ بارے تھوڑا جیہا دسو، میں تہاڈی ٹھیک رہنمائی کراں گا۔",
};

const WELCOME_FOOTER: Localised = {
  en: "Reply *menu* any time to start over",
  ur: "دوبارہ شروع کرنے کے لیے *menu* لکھیں",
  ur_roman: "Dobara shuru karne ke liye *menu* likhein",
  pa: "مُڑ شروع کرن لئی *menu* لکھو",
};

export function welcomeMessage(language: Language): {
  text: string;
  buttons: ReplyButton[];
  footer: string;
} {
  return {
    text: pick(WELCOME, language),
    footer: pick(WELCOME_FOOTER, language),
    buttons: quickActions(language),
  };
}

// ----------------------------------------------------------- Quick actions --

const GET_QUOTE: Localised = {
  en: "💼 Get a quote",
  ur: "💼 قیمت معلوم کریں",
  ur_roman: "💼 Quote lein",
  pa: "💼 ریٹ پُچھو",
};

const OUR_SERVICES: Localised = {
  en: "🧭 Our services",
  ur: "🧭 ہماری خدمات",
  ur_roman: "🧭 Hamari services",
  pa: "🧭 ساڈیاں سروسز",
};

const TALK_TO_TEAM: Localised = {
  en: "🙋 Talk to a human",
  ur: "🙋 نمائندے سے بات",
  ur_roman: "🙋 Team se baat",
  pa: "🙋 بندے نال گل",
};

/**
 * The three chips offered under an answer.
 *
 * "Get a quote" and "Our services" need no handler of their own: a tapped
 * button arrives with its title as the message text, and the representative
 * takes it from there like anything the customer typed.
 */
export function quickActions(language: Language): ReplyButton[] {
  return [
    { id: `${ACTION_BUTTON_PREFIX}capture`, title: pick(GET_QUOTE, language) },
    { id: `${ACTION_BUTTON_PREFIX}services`, title: pick(OUR_SERVICES, language) },
    { id: `${ACTION_BUTTON_PREFIX}human`, title: pick(TALK_TO_TEAM, language) },
  ];
}

// ------------------------------------------------------------ Transactional --

const RECEIPT: Record<CapturedRecord["kind"], Localised> = {
  LEAD: {
    en: "✅ Your details are with our team — reference *{reference}*.",
    ur: "✅ آپ کی تفصیلات ہماری ٹیم تک پہنچ گئی ہیں — ریفرنس *{reference}*۔",
    ur_roman: "✅ Aap ki details hamari team tak pohanch gayi hain — reference *{reference}*.",
    pa: "✅ تہاڈیاں تفصیلاں ساڈی ٹیم کول اپڑ گئیاں نیں — ریفرنس *{reference}*۔",
  },
  MEETING: {
    en: "📅 Consultation request *{reference}* — our team will confirm the time with you.",
    ur: "📅 مشاورت کی درخواست *{reference}* — ہماری ٹیم آپ سے وقت کی تصدیق کرے گی۔",
    ur_roman: "📅 Consultation request *{reference}* — hamari team aap se time confirm karegi.",
    pa: "📅 مشورے دی درخواست *{reference}* — ساڈی ٹیم تہاڈے نال ویلا پکا کرے گی۔",
  },
  TICKET: {
    en: "🎫 Support ticket *{reference}* is open — our team will get back to you here.",
    ur: "🎫 سپورٹ ٹکٹ *{reference}* کھل گیا ہے — ہماری ٹیم یہیں آپ سے رابطہ کرے گی۔",
    ur_roman: "🎫 Support ticket *{reference}* khul gaya hai — hamari team yahin aap se rabta karegi.",
    pa: "🎫 سپورٹ ٹکٹ *{reference}* کھل گیا اے — ساڈی ٹیم ایتھے ای تہاڈے نال رابطہ کرے گی۔",
  },
};

/**
 * Sent after the representative's reply when that turn created CRM records, so
 * the customer has a reference the model never had to know about.
 */
export function recordReceipt(language: Language, records: CapturedRecord[]): string {
  return records
    .map((record) => pick(RECEIPT[record.kind], language).replace("{reference}", record.reference))
    .join("\n");
}

const ESCALATED: Localised = {
  en: "🎫 I've passed this to our team — your ticket is *{reference}*.\n\nSomeone will reply here shortly. You can also call {phone} during {hours}.",
  ur: "🎫 میں نے یہ ہماری ٹیم کو بھیج دیا ہے — آپ کا ٹکٹ *{reference}* ہے۔\n\nکوئی جلد یہیں جواب دے گا۔ آپ {hours} کے دوران {phone} پر کال بھی کر سکتے ہیں۔",
  ur_roman:
    "🎫 Maine ye hamari team ko bhej diya hai — aap ka ticket *{reference}* hai.\n\nKoi jald yahin reply karega. Aap {hours} mein {phone} par call bhi kar sakte hain.",
  pa: "🎫 میں ایہہ ساڈی ٹیم نوں بھیج دِتا اے — تہاڈا ٹکٹ *{reference}* اے۔\n\nکوئی چھیتی ایتھے ای جواب دیوے گا۔ تسی {hours} وچ {phone} تے کال وی کر سکدے او۔",
};

export function escalationNotice(language: Language, reference: string): string {
  return pick(ESCALATED, language)
    .replace("{reference}", reference)
    .replace("{phone}", BRAND.contact.phone)
    .replace("{hours}", BRAND.contact.hours);
}

const MEDIA_ACK: Localised = {
  en: "📎 Thanks — I've received that and attached it to your conversation. I can't open files myself, so please also describe what you need in a message.",
  ur: "📎 شکریہ — مجھے موصول ہو گیا اور آپ کی گفتگو سے منسلک کر دیا ہے۔ میں فائل خود نہیں کھول سکتا، اس لیے براہِ کرم پیغام میں بھی بتا دیں کہ آپ کو کیا چاہیے۔",
  ur_roman:
    "📎 Shukriya — mujhe mil gaya aur aap ki conversation se attach kar diya hai. Main file khud nahi khol sakta, is liye message mein bhi bata dein aap ko kya chahiye.",
  pa: "📎 شکریہ — مینوں مل گیا تے تہاڈی گل بات نال لا دِتا اے۔ میں فائل آپ نئیں کھول سکدا، ایس لئی سنیہے وچ وی دس دیو تہانوں کیہ چاہیدا اے۔",
};

export const mediaAcknowledgement = (language: Language) => pick(MEDIA_ACK, language);

const OPTED_OUT: Localised = {
  en: "You're unsubscribed from BITSOL broadcasts. 👍\n\nYou can still message here any time — send *start* to talk to the assistant again.",
  ur: "آپ بِٹسول کے پیغامات سے ان سبسکرائب ہو گئے ہیں۔ 👍\n\nآپ یہاں کبھی بھی پیغام بھیج سکتے ہیں — دوبارہ بات کرنے کے لیے *start* لکھیں۔",
  ur_roman:
    "Aap BITSOL broadcasts se unsubscribe ho gaye hain. 👍\n\nAap yahan kabhi bhi message kar sakte hain — dobara baat karne ke liye *start* likhein.",
  pa: "تسی بِٹسول دے پیغاماں توں ان سبسکرائب ہو گئے او۔ 👍\n\nتسی ایتھے کدے وی سنیہا بھیج سکدے او — مُڑ گل کرن لئی *start* لکھو۔",
};

export const optOutConfirmation = (language: Language) => pick(OPTED_OUT, language);

const BUSY: Localised = {
  en: "Sorry, I'm having trouble replying right now. Please try again in a moment, or call us on {phone}.",
  ur: "معذرت، ابھی جواب دینے میں دشواری ہو رہی ہے۔ تھوڑی دیر بعد کوشش کریں، یا {phone} پر کال کریں۔",
  ur_roman:
    "Maazrat, abhi reply karne mein dikkat ho rahi hai. Thori der baad koshish karein, ya {phone} par call karein.",
  pa: "معافی، ہُݨے جواب دیݨ وچ اوکھ آ رہی اے۔ تھوڑی دیر بعد کوشش کرو، یا {phone} تے کال کرو۔",
};

export function busyNotice(language: Language): string {
  return pick(BUSY, language).replace("{phone}", BRAND.contact.phone);
}
